# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'personal-finance.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QTableWidget,
    QTableWidgetItem, QToolBar, QWidget)
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(790, 600)
        self.actionImport_CSV = QAction(MainWindow)
        self.actionImport_CSV.setObjectName(u"actionImport_CSV")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.actionImport_CSV.setIcon(icon)
        self.actionSave_file = QAction(MainWindow)
        self.actionSave_file.setObjectName(u"actionSave_file")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.actionSave_file.setIcon(icon1)
        self.actionSave_to_PDF = QAction(MainWindow)
        self.actionSave_to_PDF.setObjectName(u"actionSave_to_PDF")
        icon2 = QIcon()
        icon2.addFile(u":/assets/pdf.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_to_PDF.setIcon(icon2)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.WindowClose))
        self.actionExit.setIcon(icon3)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DialogInformation))
        self.actionAbout.setIcon(icon4)
        self.actionUser_Guide = QAction(MainWindow)
        self.actionUser_Guide.setObjectName(u"actionUser_Guide")
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.HelpAbout))
        self.actionUser_Guide.setIcon(icon5)
        self.actionCharts = QAction(MainWindow)
        self.actionCharts.setObjectName(u"actionCharts")
        icon6 = QIcon()
        icon6.addFile(u":/assets/charts.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCharts.setIcon(icon6)
        self.actionImportCsv = QAction(MainWindow)
        self.actionImportCsv.setObjectName(u"actionImportCsv")
        icon7 = QIcon()
        icon7.addFile(u":/assets/csv-file.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImportCsv.setIcon(icon7)
        self.actionImportCsv.setMenuRole(QAction.MenuRole.NoRole)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon8 = QIcon()
        icon8.addFile(u":/assets/undo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionUndo.setIcon(icon8)
        self.actionUndo.setMenuRole(QAction.MenuRole.NoRole)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon9 = QIcon()
        icon9.addFile(u":/assets/redo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRedo.setIcon(icon9)
        self.actionRedo.setMenuRole(QAction.MenuRole.NoRole)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon10 = QIcon()
        icon10.addFile(u":/assets/save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon10)
        self.actionSave.setMenuRole(QAction.MenuRole.NoRole)
        self.actionExportToPdf = QAction(MainWindow)
        self.actionExportToPdf.setObjectName(u"actionExportToPdf")
        self.actionExportToPdf.setIcon(icon2)
        self.actionExportToPdf.setMenuRole(QAction.MenuRole.NoRole)
        self.actionCurrency_Exchange = QAction(MainWindow)
        self.actionCurrency_Exchange.setObjectName(u"actionCurrency_Exchange")
        icon11 = QIcon()
        icon11.addFile(u":/assets/currency.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCurrency_Exchange.setIcon(icon11)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(15, 11, 761, 541))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 790, 23))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuAdvanced = QMenu(self.menubar)
        self.menuAdvanced.setObjectName(u"menuAdvanced")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionImport_CSV)
        self.menuFile.addAction(self.actionSave_file)
        self.menuFile.addAction(self.actionSave_to_PDF)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addSeparator()
        self.menuHelp.addSeparator()
        self.menuAdvanced.addAction(self.actionCharts)
        self.menuAdvanced.addAction(self.actionCurrency_Exchange)
        self.toolBar.addAction(self.actionImportCsv)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExportToPdf)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Personal Finance", None))
        self.actionImport_CSV.setText(QCoreApplication.translate("MainWindow", u"Import CSV", None))
        self.actionSave_file.setText(QCoreApplication.translate("MainWindow", u"Save to ...", None))
        self.actionSave_to_PDF.setText(QCoreApplication.translate("MainWindow", u"Save to PDF", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionUser_Guide.setText(QCoreApplication.translate("MainWindow", u"User Guide", None))
        self.actionCharts.setText(QCoreApplication.translate("MainWindow", u"Charts", None))
        self.actionImportCsv.setText(QCoreApplication.translate("MainWindow", u"ImportCsv", None))
#if QT_CONFIG(tooltip)
        self.actionImportCsv.setToolTip(QCoreApplication.translate("MainWindow", u"Import CSV", None))
#endif // QT_CONFIG(tooltip)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo", None))
#endif // QT_CONFIG(tooltip)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save", None))
#endif // QT_CONFIG(tooltip)
        self.actionExportToPdf.setText(QCoreApplication.translate("MainWindow", u"ExportToPdf", None))
#if QT_CONFIG(tooltip)
        self.actionExportToPdf.setToolTip(QCoreApplication.translate("MainWindow", u"Export to PDF", None))
#endif // QT_CONFIG(tooltip)
        self.actionCurrency_Exchange.setText(QCoreApplication.translate("MainWindow", u"Currency Exchange", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuAdvanced.setTitle(QCoreApplication.translate("MainWindow", u"Advanced", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

